#!/bin/bash
# ============================================================================
# stop_remote.sh — Stop remote training sessions
# ============================================================================
# Usage:
#   bash scripts/remote/stop_remote.sh <session_name>    # Stop specific session
#   bash scripts/remote/stop_remote.sh --all             # Stop ALL training sessions
#   bash scripts/remote/stop_remote.sh --list            # List running sessions
#
# Session names are auto-generated by train_remote.sh:
#   Format: <config>_<task>  (e.g., dp3_pour, ddp_maniflow_pour)
# ============================================================================

set -euo pipefail

trap 'echo ""; echo "Interrupted — training may still be running. Re-run stop_remote.sh to ensure stop."; exit 1' INT

SERVER="${DEX_SERVER:-dexserver}"

# Gracefully stop a single tmux session.
# Sends Ctrl+C (SIGINT) to the foreground process group via tmux send-keys,
# which correctly signals all DDP workers simultaneously.
# Waits up to 30s for graceful shutdown, then force-kills the session.
_graceful_stop() {
    local session="$1"
    local session_safe="${session//\'/\'\\\'\'}"

    if ! ssh "$SERVER" "tmux has-session -t '${session_safe}' 2>/dev/null"; then
        echo "  (session not found, nothing to stop)"
        return 0
    fi

    echo "  Sending Ctrl+C (SIGINT) to tmux pane..."
    ssh "$SERVER" "tmux send-keys -t '${session_safe}' C-c" 2>/dev/null || true

    local waited=0
    while [[ $waited -lt 30 ]]; do
        if ! ssh "$SERVER" "tmux has-session -t '${session_safe}' 2>/dev/null"; then
            echo "  Session exited gracefully after ${waited}s."
            break
        fi
        sleep 2
        waited=$((waited + 2))
    done

    if [[ $waited -ge 30 ]]; then
        echo "  SIGINT timeout, force-killing tmux session..."
        ssh "$SERVER" "tmux kill-session -t '${session_safe}' 2>/dev/null; true"
    fi

    # Post-stop GPU verification (runs whether graceful or forced)
    echo -n "  GPU memory: "
    local procs
    procs=$(ssh "$SERVER" \
        "nvidia-smi --query-compute-apps=pid,used_memory --format=csv,noheader 2>/dev/null" || true)
    if [[ -z "$procs" ]]; then
        echo "clean"
    else
        echo ""
        echo "  ⚠  GPU memory still allocated:"
        echo "$procs" | sed 's/^/      /'
        echo "  Investigate on server: nvidia-smi"
    fi
}

case "${1:-}" in
    --list|-l)
        echo "=== Active tmux sessions on $SERVER ==="
        ssh "$SERVER" "tmux list-sessions 2>/dev/null" || echo "(no active sessions)"
        exit 0
        ;;
    --all|-a)
        echo "Stopping all training sessions on $SERVER..."
        sessions=$(ssh "$SERVER" "tmux list-sessions 2>/dev/null | cut -d: -f1" || true)
        if [[ -z "$sessions" ]]; then
            echo "  (no active sessions)"
        else
            stopped=0
            for s in $sessions; do
                # Only stop this repo's training sessions (dex_-prefixed).
                [[ "$s" == dex_* ]] || continue
                echo "  [$s]"
                _graceful_stop "$s"
                stopped=$((stopped + 1))
            done
            echo "Stopped $stopped training session(s)."
        fi
        ;;
    "")
        echo "Usage: stop_remote.sh <session_name> | --all | --list" >&2
        echo ""
        echo "Active sessions:"
        ssh "$SERVER" "tmux list-sessions 2>/dev/null" || echo "  (none)"
        exit 1
        ;;
    *)
        SESSION="$1"
        if [[ ! "$SESSION" =~ ^dex_[a-zA-Z0-9_.-]+$ ]]; then
            echo "Error: invalid session name '$SESSION'. Expected format: dex_<config>_<task>[_s<seed>]" >&2
            exit 1
        fi
        echo "Stopping session: $SESSION"
        _graceful_stop "$SESSION"
        echo "Stopped."
        ;;
esac
