#!/bin/bash
# ============================================================================
# stop_remote.sh — Stop remote training sessions
# ============================================================================
# Usage:
#   bash scripts/stop_remote.sh <session_name>    # Stop specific session
#   bash scripts/stop_remote.sh --all             # Stop ALL training sessions
#   bash scripts/stop_remote.sh --list            # List running sessions
#
# Session names are auto-generated by train_remote.sh:
#   Format: <config>_<task>  (e.g., dp3_pour, ddp_maniflow_pour)
# ============================================================================

set -euo pipefail

SERVER="${DEX_SERVER:-dexserver}"

case "${1:-}" in
    --list|-l)
        echo "=== Active tmux sessions on $SERVER ==="
        ssh "$SERVER" "tmux list-sessions 2>/dev/null" || echo "(no active sessions)"
        exit 0
        ;;
    --all|-a)
        echo "Stopping ALL training sessions on $SERVER..."
        ssh "$SERVER" "tmux list-sessions 2>/dev/null | cut -d: -f1 | xargs -r -I{} tmux kill-session -t {} 2>/dev/null; true"
        echo "All sessions stopped."
        ;;
    "")
        echo "Usage: stop_remote.sh <session_name> | --all | --list" >&2
        echo ""
        echo "Active sessions:"
        ssh "$SERVER" "tmux list-sessions 2>/dev/null" || echo "  (none)"
        exit 1
        ;;
    *)
        SESSION="$1"
        echo "Stopping session: $SESSION"
        if ssh "$SERVER" "tmux kill-session -t '$SESSION' 2>/dev/null"; then
            echo "Stopped."
        else
            echo "Session '$SESSION' not found."
            echo ""
            echo "Active sessions:"
            ssh "$SERVER" "tmux list-sessions 2>/dev/null" || echo "  (none)"
            exit 1
        fi
        ;;
esac
