_target_: dexmani_policy.datasets.multi_task_dataset.MultiTaskDataset
seed: ${seed}
sampling_strategy: balanced  # 'proportional' | 'balanced' | 'weighted'
normalizer_mode: shared      # 'shared' | 'per_task'

task_names:
  - task_1
  - task_2
  - task_3

# 仅当 sampling_strategy='weighted' 时生效
task_weights:
  - 1.0
  - 1.0
  - 2.0

datasets:
  - _target_: dexmani_policy.datasets.pc_dataset.PCDataset
    zarr_path: robot_data/sim/task_1.zarr
    seed: ${seed}
    horizon: ${horizon}
    pad_before: ${eval:'${n_obs_steps} - 1'}
    pad_after: ${eval:'${n_action_steps} - 1'}
    val_ratio: 0.05
    max_train_episodes: null
    sensor_modalities: ['joint_state', 'point_cloud']

  - _target_: dexmani_policy.datasets.pc_dataset.PCDataset
    zarr_path: robot_data/sim/task_2.zarr
    seed: ${seed}
    horizon: ${horizon}
    pad_before: ${eval:'${n_obs_steps} - 1'}
    pad_after: ${eval:'${n_action_steps} - 1'}
    val_ratio: 0.05
    max_train_episodes: null
    sensor_modalities: ['joint_state', 'point_cloud']

  - _target_: dexmani_policy.datasets.pc_dataset.PCDataset
    zarr_path: robot_data/sim/task_3.zarr
    seed: ${seed}
    horizon: ${horizon}
    pad_before: ${eval:'${n_obs_steps} - 1'}
    pad_after: ${eval:'${n_action_steps} - 1'}
    val_ratio: 0.05
    max_train_episodes: null
    sensor_modalities: ['joint_state', 'point_cloud']
