# @package _global_

defaults:
  - maniflow
  - _self_

# DDP 训练: batch_size 为每卡值，总 batch = batch_size × num_gpus

policy_name: maniflow_ddp

training:
  num_gpus: 4
  gpu_ids: null

dataloader:
  batch_size: 32
  num_workers: 4

val_dataloader:
  batch_size: 32
  num_workers: 4

hydra:
  job:
    override_dirname: ${policy_name}_${task_name}
  run:
    dir: experiments/${policy_name}/${task_name}/${now:%Y-%m-%d_%H-%M}_${training.seed}
  sweep:
    dir: experiments/${policy_name}/${task_name}/${now:%Y-%m-%d_%H-%M}_${training.seed}
    subdir: ${hydra.job.num}
